import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PrivyProvider } from "@/components/PrivyProvider";
import NavBar from "@/components/NavBar";
import Marketplace from "@/components/Marketplace";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/Footer";
import OnboardingDialog from "@/components/OnboardingDialog";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PrivyProvider>
          <OnboardingDialog />
          <div className="min-h-screen bg-[url('/grid-lines.png')] bg-cover bg-center relative">
            <div className="min-h-screen bg-[url('/bg-gradient.png')] bg-cover bg-center">
              <NavBar />
              {children}
              <Marketplace />
              <Footer />
            </div>
          </div>
          <ToastContainer autoClose={3000} />
        </PrivyProvider>
      </body>
    </html>
  );
}
